platform :ios, '13.0'

target 'Example' do
  use_frameworks!

  pod 'scandit-datacapture-frameworks-label', :path => '../'

  # REPLACE-BEGIN
  pod 'scandit-datacapture-frameworks-barcode', :path => '../../scandit-datacapture-frameworks-barcode'
  pod 'scandit-datacapture-frameworks-core', :path => '../../scandit-datacapture-frameworks-core'
  # REPLACE-END
end
